import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import { MdMovie } from "react-icons/md";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar/navbar"
export default function Home() {
  return (
    <>
      <Head>
        <title>BookMyMovie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_bg1.png" />
      </Head>
      <div>
        <main className={styles.main}>
          <Navbar/>
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
